#!/bin/sh

echo "Building for Windows ..."
GOOS=windows go build -o bin/windows/bot.exe cmd/alvisd/main.go

echo "Building for Mac (darwin) ..."
GOOS=darwin go build -o bin/macos/bot cmd/alvisd/main.go

echo "Building for Linux ..."
env GOOS=linux GOARCH=386 CGO_ENABLED=0 go build -o bin/linux/bot cmd/alvisd/main.go
